# Generated by Django 4.0 on 2021-12-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=60)),
                ('CourseNumber', models.IntegerField(blank=True)),
                ('InstructorName', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.FloatField(blank=True)),
            ],
        ),
    ]
